stages:
  - build
  - deploy

build dns:
  stage: build
  tags:
    - docker-image-builder
  script:
    - set -x
    - docker build . -f ./docker/dns/Dockerfile -t mailbroker_dns:${CI_COMMIT_SHA} -t mailbroker_dns:latest

#build exim:
#  stage: build
#  tags:
#    - docker-image-builder
#  script:
#    - set -x
#    - docker build . -f ./docker/exim/Dockerfile -t mailbroker_exim:${CI_COMMIT_SHA} -t mailbroker_exim:latest

deploy from docker-compose.deploy.yml:
  stage: deploy
  tags:
    - deploy
  script:
    - set -x
    - DEPLOY_DIR=~/deploy-from-dc/mailbroker
    - mkdir -p ${DEPLOY_DIR}
    - cp docker-compose.deploy.yml ${DEPLOY_DIR}
    - docker-compose -f ${DEPLOY_DIR}/docker-compose.deploy.yml up -d dns