version: '3'
services:
  exim:
    build: ./exim
    ports:
      - ${PORT_EXIM}:${PORT_EXIM}
    environment:
      EXIM_DOMAIN: ${EXIM_DOMAIN}
      EXIM_DEBUG: ${EXIM_DEBUG}
      EXIM_INCOMING_MAIL_MAX_SIZE: ${EXIM_INCOMING_MAIL_MAX_SIZE}
      EXIM_MAIL_USER: ${EXIM_MAIL_USER}
      EXIM_MAIL_PASS: ${EXIM_MAIL_PASS}
      PORT_EXIM: ${PORT_EXIM}
      PORT_API: ${PORT_API}
      TZ: ${TZ}
    restart: always
    hostname: ${EXIM_DOMAIN}
    networks:
      mt:
        ipv4_address: ${IP_EXIM}
    dns: ${IP_DNS_RESOLVER}
    depends_on:
      - dns
  spamassassin:
    build: ./spamassassin
    environment:
      PORT_SPAMASSASSIN: ${PORT_SPAMASSASSIN}
      TZ: ${TZ}
    hostname: spamassassin
    networks:
      mt:
        ipv4_address: ${IP_SPAMASSASSIN}
    dns: ${IP_DNS_RESOLVER}
    depends_on:
      - dns
  mongo:
    image: mongo
    hostname: mongo
    networks:
      mt:
        ipv4_address: ${IP_MONGO}
    dns: ${IP_DNS_RESOLVER}
    depends_on:
      - dns
  test-compose:
    build: ./test-compose
    volumes:
      # dev volumes for hot reload
      - ./test-compose:/srv/
      # test letters
      - ./test-letters:/srv/test-letters
    environment:
      RUN_TESTS: ${RUN_TESTS}
      EXIM_DOMAIN: ${EXIM_DOMAIN}
      PORT_API: ${PORT_API}
      PORT_EXIM: ${PORT_EXIM}
      PORT_SPAMASSASSIN: ${PORT_SPAMASSASSIN}
      TZ: ${TZ}
    hostname: test-compose
    networks:
      mt:
        ipv4_address: ${IP_TEST_COMPOSE}
    dns: ${IP_DNS_RESOLVER}
    depends_on:
      - api
      - dns
  dns:
    build: ./dns
    environment:
      PORT_DNS: ${PORT_DNS}
      DNS_CACHE_MIN_TTL: ${DNS_CACHE_MIN_TTL}
      DNS_CACHE_MAX_NEGATIVE_TTL: ${DNS_CACHE_MAX_NEGATIVE_TTL}
      DNS_DEBUG: ${DNS_DEBUG}
      DNS_STATISTICS_INTERVAL: ${DNS_STATISTICS_INTERVAL}
      DNS_LOG_QUERIES: ${DNS_LOG_QUERIES}
      DNS_LOG_REPLIES: ${DNS_LOG_REPLIES}
      DNS_LOG_SERVFAIL: ${DNS_LOG_SERVFAIL}
      TZ: ${TZ}
    restart: always
    hostname: dns
    networks:
      mt:
        ipv4_address: ${IP_DNS_RESOLVER}
  api:
    build: ./api
    volumes:
      # dev volumes for hot reload
      - ./api/index.js:/srv/index.js
      - ./api/mail.js:/srv/mail.js
      - ./api/lib:/srv/lib
      - ./api/test:/srv/test
      # test letters
      - ./test-letters:/test-letters
    environment:
      PORT_SPAMASSASSIN: ${PORT_SPAMASSASSIN}
      PORT_API: ${PORT_API}
      API_INCOMING_MAIL_MAX_SIZE: ${API_INCOMING_MAIL_MAX_SIZE}
      API_MAX_MAIL_COUNT: ${API_MAX_MAIL_COUNT}
      API_CATCH_MTA_ALL: ${API_CATCH_MTA_ALL}
      API_CATCH_MTA_TO: ${API_CATCH_MTA_TO}
      API_REPLY_MTA_REPORT_ALL: ${API_REPLY_MTA_REPORT_ALL}
      API_REPLY_MTA_REPORT_TO: ${API_REPLY_MTA_REPORT_TO}
      EXIM_MAIL_FROM: ${EXIM_MAIL_FROM}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SPAMASSASSIN_MAX_MSG_SIZE: ${SPAMASSASSIN_MAX_MSG_SIZE}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      EXIM_DOMAIN: ${EXIM_DOMAIN}
      EXIM_MAIL_USER: ${EXIM_MAIL_USER}
      EXIM_MAIL_PASS: ${EXIM_MAIL_PASS}
      TZ: ${TZ}
      IP_DNS_RESOLVER: ${IP_DNS_RESOLVER}
    restart: always
    ports:
      - ${PORT_API}:${PORT_API}
    hostname: api
    networks:
      mt:
        ipv4_address: ${IP_API}
    dns: ${IP_DNS_RESOLVER}
    depends_on:
      - dns
      - mongo
      - exim
      - spamassassin

  website:
    image: "nginx:alpine"
    environment:
      WEB_DOMAIN: "${WEB_DOMAIN}"
      PORT_WEBSITE: "${PORT_WEBSITE}"
    # dev volumes
    volumes:
      - ./website/nginx.conf:/etc/nginx/conf.d/mysite.template
      - ./website/www:/srv
    ports:
      - "${PORT_WEBSITE}:${PORT_WEBSITE}"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    hostname: website
    networks:
      mt:
        ipv4_address: ${IP_WEBSITE}
    dns: ${IP_DNS_RESOLVER}
    depends_on:
      - dns
      - mongo
      - exim
      - spamassassin

networks:
  mt:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_SUBNET}
